import { Nunito } from "next/font/google";
const font = Nunito({
  subsets: ["latin"],
});

import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Clone AirB&B App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
